site_name: "FEBio 4.12 - Theory Manual"
site_description: This manual provides the theoretical background for FEBio.
site_author: FEBio Team
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.external.links
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.details
extra_javascript:
  - js/mathjax_config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Preface: index.md
  - Chapter 1 - Introduction:
    - 1.1 Overview of FEBio: theory/chapter1/1.1-overview-of-febio.md
    - 1.2 About this document: theory/chapter1/1.2-about-this-document.md
  - Chapter 2 - Continuum Mechanics:
    - 2.1 Vectors and Tensors: theory/chapter2/2.1-vectors-and-tensors.md
    - 2.2 The Directional Derivative: theory/chapter2/2.2-the-directional-derivative.md
    - 2.3 Cauchy Stress: theory/chapter2/2.3-cauchy-stress.md
    - 2.4 Axioms of Conservation: theory/chapter2/2.4-axioms-of-conservation.md
    - 2.5 Kinematics of the Continuum: theory/chapter2/2.5-kinematics-of-the-continuum.md
    - 2.6 Hyperelasticity: theory/chapter2/2.6-hyperelasticity.md
    - 2.7 Biphasic Material: theory/chapter2/2.7-biphasic-material.md
    - 2.8 Biphasic-Solute Material: theory/chapter2/2.8-biphasic-solute-material.md
    - 2.9 Triphasic and Multiphasic Materials: theory/chapter2/2.9-triphasic-and-multiphasic-materials.md
    - 2.10 Constrained Reactive Mixture of Solids: theory/chapter2/2.10-constrained-reactive-mixture-of-solids.md
    - 2.11 Equilibrium Swelling: theory/chapter2/2.11-equilibrium-swelling.md
    - 2.12 Chemical Reactions: theory/chapter2/2.12-chemical-reactions.md
    - 2.13 Fluid Mechanics: theory/chapter2/2.13-fluid-mechanics.md
    - 2.14 Fluid-Structure Interactions: theory/chapter2/2.14-fluid-structure-interactions.md
    - 2.15 Hybrid Biphasic Material: theory/chapter2/2.15-hybrid-biphasic-material.md
    - 2.16 Fluid-Solutes Analyses: theory/chapter2/2.16-fluid-solutes-analyses.md
  - Chapter 3 - The Nonlinear FE Method:
    - 3.1 Weak formulation for Solid Materials: theory/chapter3/3.1-weak-formulation-for-solid-materials.md
    - 3.2 Weak formulation for biphasic materials: theory/chapter3/3.2-weak-formulation-for-biphasic-materials.md
    - 3.3 Weak Formulation for Biphasic-Solute Materials: theory/chapter3/3.3-weak-formulation-for-biphasic-solute-materials.md
    - 3.4 Weak Formulation for Multiphasic Materials: theory/chapter3/3.4-weak-formulation-for-multiphasic-materials.md
    - 3.5 Computational Fluid Dynamics: theory/chapter3/3.5-computational-fluid-dynamics.md
    - 3.6 Weak Formulation for FSI: theory/chapter3/3.6-weak-formulation-for-fsi.md
    - 3.7 Weak Formulation for BFSI: theory/chapter3/3.7-weak-formulation-for-bfsi.md
    - 3.8 Weak Formulation for Fluid-Solutes Analyses: theory/chapter3/3.8-weak-formulation-for-fluid-solutes-analyses.md
    - 3.9 Newton-Raphson Method: theory/chapter3/3.9-newton-raphson-method.md
    - 3.10 Generalized $\alpha-$Method: theory/chapter3/3.10-generalized-alpha-method.md
