site_name: "FEBio 4.12 - Theory Manual"
site_description: This manual provides the theoretical background for FEBio.
site_author: FEBio Team
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.external.links
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.details
extra_javascript:
  - js/mathjax_config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Preface: index.md
  - Chapter 1 - Introduction:
    - 1.1 Overview of FEBio: theory/chapter1/1.1-overview-of-febio.md
    - 1.2 About this document: theory/chapter1/1.2-about-this-document.md
  - Chapter 2 - Continuum Mechanics:
    - 2.1 Vectors and Tensors: theory/chapter2/2.1-vectors-and-tensors.md
    - 2.2 The Directional Derivative: theory/chapter2/2.2-the-directional-derivative.md
    - 2.3 Cauchy Stress: theory/chapter2/2.3-cauchy-stress.md
    - 2.4 Axioms of Conservation: theory/chapter2/2.4-axioms-of-conservation.md
    - 2.5 Kinematics of the Continuum: theory/chapter2/2.5-kinematics-of-the-continuum.md
    - 2.6 Hyperelasticity: theory/chapter2/2.6-hyperelasticity.md
    - 2.7 Biphasic Material: theory/chapter2/2.7-biphasic-material.md
    - 2.8 Biphasic-Solute Material: theory/chapter2/2.8-biphasic-solute-material.md
    - 2.9 Triphasic and Multiphasic Materials: theory/chapter2/2.9-triphasic-and-multiphasic-materials.md
    - 2.10 Constrained Reactive Mixture of Solids: theory/chapter2/2.10-constrained-reactive-mixture-of-solids.md
    - 2.11 Equilibrium Swelling: theory/chapter2/2.11-equilibrium-swelling.md
    - 2.12 Chemical Reactions: theory/chapter2/2.12-chemical-reactions.md
    - 2.13 Fluid Mechanics: theory/chapter2/2.13-fluid-mechanics.md
    - 2.14 Fluid-Structure Interactions: theory/chapter2/2.14-fluid-structure-interactions.md
    - 2.15 Hybrid Biphasic Material: theory/chapter2/2.15-hybrid-biphasic-material.md
    - 2.16 Fluid-Solutes Analyses: theory/chapter2/2.16-fluid-solutes-analyses.md
  - Chapter 3 - The Nonlinear FE Method:
    - 3.1 Weak formulation for Solid Materials: theory/chapter3/3.1-weak-formulation-for-solid-materials.md
    - 3.2 Weak formulation for biphasic materials: theory/chapter3/3.2-weak-formulation-for-biphasic-materials.md
    - 3.3 Weak Formulation for Biphasic-Solute Materials: theory/chapter3/3.3-weak-formulation-for-biphasic-solute-materials.md
    - 3.4 Weak Formulation for Multiphasic Materials: theory/chapter3/3.4-weak-formulation-for-multiphasic-materials.md
    - 3.5 Computational Fluid Dynamics: theory/chapter3/3.5-computational-fluid-dynamics.md
    - 3.6 Weak Formulation for FSI: theory/chapter3/3.6-weak-formulation-for-fsi.md
    - 3.7 Weak Formulation for BFSI: theory/chapter3/3.7-weak-formulation-for-bfsi.md
    - 3.8 Weak Formulation for Fluid-Solutes Analyses: theory/chapter3/3.8-weak-formulation-for-fluid-solutes-analyses.md
    - 3.9 Newton-Raphson Method: theory/chapter3/3.9-newton-raphson-method.md
    - 3.10 Generalized $\alpha-$Method: theory/chapter3/3.10-generalized-alpha-method.md
  - Chapter 4 - Element Library:
    - 4.1 Solid Elements: theory/chapter4/4.1-solid-elements.md
    - 4.2 Shell Elements: theory/chapter4/4.2-shell-elements.md
  - Chapter 5 - Constitutive Models:
    - 5.1 Linear Elasticity: theory/chapter5/5.1-linear-elasticity.md
    - 5.2 Compressible Materials: theory/chapter5/5.2-compressible-materials.md
    - 5.3 Nearly-Incompressible Materials: theory/chapter5/5.3-nearly-incompressible-materials.md
    - 5.4 Viscoelasticity: theory/chapter5/5.4-viscoelasticity.md
    - 5.5 Reactive Damage Mechanics: theory/chapter5/5.5-reactive-damage-mechanics.md
    - 5.6 Reactive Plasticity: theory/chapter5/5.6-reactive-plasticity.md
    - 5.7 Reactive Elastoplastic Damage Mechanics: theory/chapter5/5.7-reactive-elastoplastic-damage-mechanics.md
    - 5.8 Hydraulic Permeability: theory/chapter5/5.8-hydraulic-permeability.md
    - 5.9 Solute Diffusivity: theory/chapter5/5.9-solute-diffusivity.md
    - 5.10 Solute Solubility: theory/chapter5/5.10-solute-solubility.md
    - 5.11 Osmotic Coefficient: theory/chapter5/5.11-osmotic-coefficient.md
    - 5.12 Active Contraction Model: theory/chapter5/5.12-active-contraction-model.md
    - 5.13 Prescribed Active Contraction: theory/chapter5/5.13-prescribed-active-contraction.md
    - 5.14 Chemical Reaction Production Rate: theory/chapter5/5.14-chemical-reaction-production-rate.md
    - 5.15 Specific Reaction Rate: theory/chapter5/5.15-specific-reaction-rate.md
    - 5.16 Viscous Fluids: theory/chapter5/5.16-viscous-fluids.md
  - Chapter 6 - Dynamics:
    - 6.1 Newmark Integration: theory/chapter6/6.1-newmark-integration.md
    - 6.2 Elastodynamics: theory/chapter6/6.2-elastodynamics.md
    - 6.3 Rigid Body Dynamics: theory/chapter6/6.3-rigid-body-dynamics.md
  - Chapter 7 - Contact and Coupling:
    - 7.1 Sliding Interfaces: theory/chapter7/7.1-sliding-interfaces.md
    - 7.2 Biphasic Contact: theory/chapter7/7.2-biphasic-contact.md
    - 7.3 Biphasic-Solute Contact: theory/chapter7/7.3-biphasic-solute-contact.md
    - 7.4 Multiphasic Contact: theory/chapter7/7.4-multiphasic-contact.md
    - 7.5 Tied Contact: theory/chapter7/7.5-tied-contact.md
    - 7.6 Tied Biphasic Contact: theory/chapter7/7.6-tied-biphasic-contact.md
    - 7.7 Tied Multiphasic Contact: theory/chapter7/7.7-tied-multiphasic-contact.md
    - 7.8 Tied Fluid Interface: theory/chapter7/7.8-tied-fluid-interface.md
    - 7.9 Rigid Connectors: theory/chapter7/7.9-rigid-connectors.md
    - 7.10 Rigid-Deformable Coupling: theory/chapter7/7.10-rigid-deformable-coupling.md
    - 7.11 Nonlinear Constraints: theory/chapter7/7.11-nonlinear-constraints.md
  - Chapter 8 - Optimization:
    - 8.1 The Objective Function: theory/chapter8/8.1-the-objective-function.md
    - 8.2 The Levenberg-Marquardt Method: theory/chapter8/8.2-the-levenberg-marquardt-method.md
  - Appendix A - Tensor Calculus:
    - A.1 Second-Order Tensors: theory/chapterA/A.1-second-order-tensors.md
    - A.2 Higher Order Tensors: theory/chapterA/A.2-higher-order-tensors.md
